#!/bin/sh

# use this script to create a symlink
# to the root of this app
# and (re)start nginx

# point symlink to current app root
root=$(cd test/dummy && pwd -P)
link=/usr/local/nginx/html/http_push
sudo rm -f $link 
sudo ln -s $root $link

# start or restart nginx (and shutdown apache)
pidfile='usr/local/nginx/logs/nginx.pid'
[ -r $pidfile ] && ps -p `cat $pidfile` > /dev/null
if [ $? -eq 0 ]; then
    sudo /usr/local/nginx/sbin/nginx -s reload
else
    sudo /etc/init.d/apache2 stop
    sudo /usr/local/nginx/sbin/nginx
fi

# take a look
sudo lsof -nPi | grep "nginx \| apache"
